//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurongEnrollment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnrollmentEntities : DbContext
    {
        public EnrollmentEntities()
            : base("name=EnrollmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<EducationAttainments> EducationAttainments { get; set; }
        public virtual DbSet<EnrolledSubjects> EnrolledSubjects { get; set; }
        public virtual DbSet<Enrollments> Enrollments { get; set; }
        public virtual DbSet<GradeLevels> GradeLevels { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<SchoolYears> SchoolYears { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<StandardFees> StandardFees { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<AspNetUserDetails> AspNetUserDetails { get; set; }
        public virtual DbSet<Alumni> Alumni { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Gradings> Gradings { get; set; }
    }
}
