//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurongEnrollment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolledSubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnrolledSubjects()
        {
            this.Grades = new HashSet<Grades>();
        }
    
        public string Id { get; set; }
        public string EnrollmentId { get; set; }
        public string ScheduleId { get; set; }
        public Nullable<decimal> Grade { get; set; }
    
        public virtual Schedules Schedules { get; set; }
        public virtual Enrollments Enrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grades> Grades { get; set; }
    }
}
