//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurongEnrollment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public string Id { get; set; }
        public string EnrolledSubjectId { get; set; }
        public string GradingId { get; set; }
        public string Grade { get; set; }
    
        public virtual EnrolledSubjects EnrolledSubjects { get; set; }
        public virtual Gradings Gradings { get; set; }
    }
}
