//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurongEnrollment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardFees
    {
        public string Id { get; set; }
        public string GradeLevelId { get; set; }
        public string SchoolYearId { get; set; }
        public string FeeName { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
    
        public virtual GradeLevels GradeLevels { get; set; }
        public virtual SchoolYears SchoolYears { get; set; }
    }
}
